name: Install all from source
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        pg: [16, 15, 14]
    name: Postgresql ${{ matrix.pg }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Postgresql
        run: |
          # add the repo
          sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          # Import the repository signing key:
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          # Update the package lists:
          sudo apt-get update
          # Install
          sudo apt-get install -y "postgresql-${{ matrix.pg }}"
          sudo apt-get install -y gcc make g++ postgresql-server-dev-${{ matrix.pg }}
          sudo apt-get install -y -V ca-certificates lsb-release wget

      - name: Install AWS SDK
        run: |
          git clone https://github.com/aws/aws-sdk-cpp.git
          cd aws-sdk-cpp/
          git checkout 1.9.263
          git submodule update --init --recursive
          mkdir build
          cd build
          cmake -DBUILD_ONLY="s3;core;config;sts;cognito-identity;transfer;identity-management" -DCMAKE_CXX_FLAGS=-Wno-error=deprecated-declarations ..
          make 
          sudo make install

      - name: Install Arrow
        run: |
          git clone https://github.com/apache/arrow.git
          cd arrow
          git checkout apache-arrow-7.0.1
          cd cpp
          mkdir build
          cd build
          cmake  -DARROW_PARQUET=ON -DARROW_S3=ON -DARROW_WITH_SNAPPY=ON ..
          make
          sudo make install
    
      - name: Install Extension
        run: |
          git clone 	https://github.com/pgspider/parquet_s3_fdw.git
          cd parquet_s3_fdw
          git checkout v1.0.0	
          sudo apt-get install postgresql-server-dev-15
          sudo su - postgres
          make USE_PGXS=1 install
