name: CI
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        pg: [16, 15, 14]
    name: Postgresql ${{ matrix.pg }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Postgresql
        run: |
          # add the repo
          sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          # Import the repository signing key:
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          # Update the package lists:
          sudo apt-get update
          # Install
          sudo apt-get install -y "postgresql-${{ matrix.pg }}"
          sudo apt-get install -y gcc make g++ postgresql-server-dev-${{ matrix.pg }}

      - name: Install Arrow
        run: |
          bash code/install_arrow.sh

      - name: Install AWS SDK
        run: |
          git clone https://github.com/aws/aws-sdk-cpp  --recurse-submodules --branch 1.11.91 --single-branch
          mkdir /sdk_build
          cd /sdk_build
          sudo cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/include/aws -DCMAKE_INSTALL_PREFIX=/usr/include/aws -DBUILD_ONLY="s3"
          sudo nproc | xargs -I % make -j% DESTDIR=/
          sudo nproc | xargs -I % make -j% DESTDIR=/ install
          
      - name: Clone
        run: |
          git clone https://github.com/pgspider/parquet_s3_fdw
          mkdir data
          cp -r parquet_s3_fdw/data/* data/

      - name: setup minio
        run: |
          bash code/initminio.sh

      - name: try and compile a thing...
        run: |
          cd parquet_s3_fdw
          make USE_PGXS=1 install
