name: PGXMAN install
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        pg: [16, 15, 14]
    name: Postgresql ${{ matrix.pg }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Postgresql
        run: |
          # add the repo
          sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          # Import the repository signing key:
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          # Update the package lists:
          sudo apt-get update
          # Install
          sudo apt-get install -y "postgresql-${{ matrix.pg }}"
          sudo apt-get install -y gcc make g++ postgresql-server-dev-${{ matrix.pg }}
    
      - name: Install pgxman
        run: |
          downloader https://apt.pgxman.com/pgxman-keyring.gpg /usr/share/keyrings/pgxman-cli.gpg
          echo "deb [arch=${_arch} signed-by=/usr/share/keyrings/pgxman-cli.gpg] https://apt.pgxman.com/cli stable main" | ${SUDO} tee /etc/apt/sources.list.d/pgxman-cli.list >/dev/null
          sudo apt update
          sudo apt install -y pgxman

        ensure ${SUDO} apt install -y "${PGXMAN_INSTALLER_DEBIAN_PACKAGE_DIR}/pgxman_linux_${_arch}.deb"
      - name: Install s3_parquet_fdw
        run: |
          pgxman install s3_parquet_fdw
          
